---
title: "September 2023 Daily Notebook Post Log"
author: "Chris Mantegna"
date: "2023-09"
categories: ["monthly goals", "daily log"]
format:
  html:
    toc: true
---

# Daily Log

## 30 September 2023
- Saturday. 

## 29 September 2023

## 28 September 2023
- Kicked off lab meetings for the quarter with lab notebook convo and cinnamon rolls. 
- Met with Camille to chat through code/ data analysis for the YI eDNA project.
- Attended the GPC x GPA lunch meeting.
- Did some reading about biomarkers in the Principles of Ecotoxicology before attending my weekly Black Grad Student Group.

## 27 September 2023
- The first day of classes and my first day as a TA Attended the CoE Queer Affinity Group Social.

## 26 September 2023
- Writing and scheduling accountability group planning and lunch. Set up my new desk area and walked my spaces for classes/ quiz sections.

## 25 September 2023
- BCA Assay workflow with Alison in Tacoma.

## 24 September 2023
- Sunday.

## 23 September 2023
- Saturday.

## 22 September 2023
- Dissections in Tacoma, finished the first 130 of 308 samples.

## 21 September 2023
- Prep for TAing ENVIR 100. Lab Meeting where we discussed new format and schedule for lab meetings.

## 20 September 2023
- Dissections in Tacoma. Innovation Grant Content meeting with Savannah, Roslaind, Chante, and Angel.
- Made welcome goodie cups for the grads in the lab.

## 19 September 2023
- Cleaned up the grad office spaces with Zach.
- Julia meeting and BIMS ICB Issue meeting. BIMS meeting focused on how to write a discussion section in your paper.

## 18 September 2023
- Dissections in Tacoma.

## 17 September 2023
- Sunday.

## 16 September 2023
- Saturday. Dissections in Tacoma.

## 15 September 2023
- Reveling in the glory that was back to back Beyonce.

## 14 September 2023
- Working with Tiara in the morning and getting ready for Beyonce in Seattle.

## 13 September 2023
- Dissections in Tacoma. Grabbing Tiara Moore of BIMS fame from the SEATAC for a few days of fun. 

## 12 September 2023
- Celebrating my bday in Vancouver/ Seattle.

## 11 September 2023
- Beyonce in Vancouver, BC.

## 10 September 2023
- Sunday.

## 09 September 2023
- Saturday. Dissections in Tacoma.

## 08 September 2023
- Dissections in Tacoma.

## 07 September 2023
- Attended Pubathon for the first time. Met with Sean McDonald to request he join my committee and he agreed. I feel confident his addition will add some depth and breadth in community science and some alternative views on enforcing positive changes in STEM pedagogy. Ended the day with my Black Grad Group.

## 06 September 2023
- Dissections in Tacoma. Met with Alison to review what we're aiming for in our work.

## 05 September 2023
- Easy day today. I'm wrapping up simple tasks for Innovation Grant meetings, BIMS eDNA at CALeDNA trip expenses and preparing for Tacoma Lab time.  I set up my home desk with my new laptop dock and next I'll be working on my lab webpage. Today's goal is just to get it up and running, but when it comes to customization I want to sync the work with the same typography as UW. That information can be found here: https://www.washington.edu/brand/graphic-elements/font-download/. 

## 04 September 2023
- Labor Day.

## 03 September 2023
- Sunday.

## 02 September 2023
- Saturday.

## 01 September 2023  
- Kicked off the first day of September meeting with Logan to go over her REU paper edits. I attended the Gardell Lab meeting and made sure to set up some bench time in her lab over the next few weeks.
