---
title: "November 2023 Goals"
author: "Chris Mantegna"
date: "2023-11-01"
categories: ["monthly goals", "daily entries"]
format:
  html:
    toc: true
html_dependencies:
  - name: "bootstrap"
    version: "4.3.1"
    src: "https://stackpath.bootstrapcdn.com"
    stylesheet: "bootstrap.min.css"
    script: "bootstrap.min.js"
---

# Monthly Goals

## November Goals

*Knowing this is a short month because I will spend one week away at the
NABS Dive Summit and we will run into Thanksgiving, my monthly goals are
succinct and build upon existing progress.*

- Get through eDNA bioinformatics pipeline from CALeDNA trip <div class="progress">
  <div class="progress-bar" role="progressbar" style="width: 10%;" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">10%</div>
</div>

-   Outline & draft p450 manuscript

    ::: progress
    ::: {.progress-bar role="progressbar" style="width: 15%;" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"}
    15%
    :::
    :::

-   Prepare poster for AGU in December

    ::: progress
    ::: {.progress-bar role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"}
    0%
    :::
    :::

## October Goal Recap

-   Finish all BCA assays and p450 assays on initial 126 sample subset.

    ::: progress
    ::: {.progress-bar role="progressbar" style="width: 100%;" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"}
    100%
    :::
    :::

-   Prepare for first committee meeting

    ::: progress
    ::: {.progress-bar role="progressbar" style="width: 100%;" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"}
    100%
    :::
    :::

-   Get through eDNA bioinformatics pipeline from CALeDNA trip

    ::: progress
    ::: {.progress-bar role="progressbar" style="width: 10%;" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"}
    10%
    :::
    :::

## October Goal Reflection

*What worked, what didn't, where can I improve*

#### What Worked

-   I planned my bench time and put it on my calendar.
-   I set a meeting date for the committee meeting to meet a goal of
    bypass in Winter Quarter.

#### What Didn't

-   I didn't follow- up on data availability or process fast enough.\
-   I didn't spend my time waiting for data to clarify the workflow for
    eDNA bioinformatics pipeline.

#### Improve

-   Spend time at the beginning of each week not just mapping out
    'outside' obligations but tasks that are involved in my own work.
-   Block dedicated time for my work, not just work impacting others. Do
    this by breaking down to the task- level of the project and then
    adding individual tasks to my calendar.
-   Schedule 'bench' time for coding and computer- based work.
