---
title: "December 2023 Daily Notebook Post Log"
author: "Chris Mantegna"
date: "2023-12"
categories: ["monthly goals", "daily log"]
format:
  html:
    toc: true
---

# Daily Log

## 31 December 2023

- Sunday. New Year's Eve. Off.

## 30 December 2023

- Saturday. Off.

## 29 December 2023

- Writing accountability with Taylor
- Attended Science Hour to tie up some loose ends and chat about a potential grant opportunity.
- Finalized Logan's poster with Logan and Camille and sent it to the printer!

## 28 December 2023

- Lab meeting where we went over draft talks and presentations for SICB. 
- Worked on the draft of my SICB talk by continuing to work through new code/ pipeline from Rachel.

## 27 December 2023

- FAB end of year retrospective and project planning for 2024.
- Met with Ly via Zoom to discuss supplies, schedules and next steps for January and February.

## 26 December 2023

- In lab working on dissections.
- Working on physical intertidal survey results visualizations for my SICB presentation.

## 25 December 2023

- Christmas Day. Off. 

## 24 December 2023

- Sunday. Christmas Eve. Off.

## 23 December 2023

- Saturday. Data cleaning of the MARINe data for Logan's work.

## 22 December 2023

- Attended science hour to get help with moving my data to and from Gannett.
- Worked on more tissue dissections.

## 21 December 2023

- Lab meeting. DEI centered meeting.
- Work on eDNA and Yellow Island visualizations for Logan and myself.
- Wrapped up loose ends and emails for the year. 

## 20 December 2023

- Christmas errands!

## 19 December 2023

- UWT lab day. Met with Ly in person to talk through next steps. 
- Started dissecting tissue samples for repeat p450 and SOD assays since the tissues are out. The goal is to have all tissue dissected and ready for homogenization by January 9th.
- Attended BIMS Issue final ICB workshop. The deadlines are less stringent than I expected so that was a huge relief to the timeline I thought I was up against.

## 18 December 2023

- I crossed over to the dark side and purchased a Macbook... 
- Attended the final teaching team meeting for fall, finished last minute grading discrepancies/ tied up loose ends/ etc.
- Met with Logan to work on poster layout/ design.
- Confirmed the SOD kit ordering with Steven.

## 17 December 2023

- Sunday. Finished grading for ENV 100.
- Completed and submitted feedback and reimbursement to BIMS.
- Worked on poster visualizations with Logan.
- Setup labwork schedule with Ly for UWT work this week.

## 16 December 2023

- Saturday. Day off.

## 15 December 2023

- Travel from AGU to Seattle. Took over 14 hours to get home.

## 14 December 2023

- Final AGU exhibition day. Tabled and broke down the exhibit for Lynnette to ship.
- Attended Art & Science Plenary from Rebecca Mendez, afternoon poster session, BGG virtual group meeting, and LGBTQIA AGU mixer.

## 13 December 2023

- Second full day of exhibition. 
- Attended morning poster session and the Science and Society oral presentations before the exhibit opened.
- Over lunch I attended the STEM to STEAM Town Hall and the afternoon poster session. After the end of the exhibit hours I attended a Town Hall on open science notebooks and how to turn them into an interactive publication companion to the paper product. 

## 12 December 2023

- First full day of exhibition.
- Attended the Student & ECR morning session and stopped by BIMS member posters prior to exhibit opening.
- Attended the Pyrocene Plenary from Stephen Pyne, the Community Science publication opportunities session given by Julia Parrish. I wrapped up the evening at the UW mixer and left that to attend the Town Hall Session on Open Science practices and methods to increase access and usability.

## 11 December 2023

- Setup AGU booth and met my co-exhibitor, Lynnette. The Exhibit Hall opens late afternoon, so we got our booth ready and attended sessions of interest.
- Attended morning poster sessions, the ocean science student discussions, and the Climate, Health, and Environmental Justice salon in the evening.

## 10 December 2023

- Sunday. Travel to AGU.
- Checked into the conference, setup the app and created a schedule for the week.

## 09 December 2023

- Saturday. Day Off.

## 08 December 2023

- Writing accountability with Taylor and FAB accountability goal review meetings.
- Started knocking out some grading.

## 07 December 2023

- Attended lab meeting and facilitated the DEI portion of the meeting. 
- Worked on Yellow Island visualizations in preparation for my meeting with Logan.
- Met with Logan to review poster design, text, visualizations.
- BGG group in the afternoon.

## 06 December 2023

- Administered the written portion of the final in ENV 100 and attended the teaching team meeting to divide up final grading responsibilities.
- Worked on the reworked version of the WDFW presentation.
- Gave the WDFW presentation with Alison, Ly, Jim Gawel, Danielle Nordstrom, Mariko Langness, Molly Shuman- Goodier, and Luisa Harding. It went well. It was an overview of our plan and process. It was not my best presentation, but it did provoke some good conversation and suggestions for next steps and collaborations in the future. 
- Finished all assignment grading up until the final and final project (not submitted yet).


## 05 December 2023

- Administered ENV 100 final in quiz sections.
- Worked on WDFW presentation and data. The data incorrect and the level of incorrect cannot be corrected on the computational end. I'm going to rework the presentation framing and data share.

## 04 December 2023

- Attended ENV 100 teaching team meeting and lecture.
- Read resources from Alison re: inflated p450 values/ made a plan of attack for verifying fluorescence inflation by agent versus mussel activity.
- Working on p450 data to present on Wednesday. Since the data is a bit off, I'm plotting sites to see what trends I can look at the are fair to share with some accuracy.

## 03 December 2023

- Sunday. 
- Went into UWT lab to run a few test dilutions and alternative sample preparation for the BCA and p450 plates to help identify how to mitigate the super high values we received.

## 02 December 2023

- Saturday. 
- Grading for ENV 100.
- Worked on p450 draft.

## 01 December 2023

- Attended ENV lecture, FAB accountability meetng, and 555.
- Met with Ly to discuss p450 data and next steps for the SOD process.
- Worked on p450 data and reached out for the last data for Logan's work.
- Submitted my abstract on eDNA and mentorship work to UN Ocean Decades.
- Ended the workday with a meeting with Alison re: p450 data.
