---
title: "December 2023 Goals"
author: "Chris Mantegna"
date: "2023-12-01"
categories: ["monthly goals", "daily entries"]
format:
  html:
    toc: true
html_dependencies:
  - name: "bootstrap"
    version: "4.3.1"
    src: "https://stackpath.bootstrapcdn.com"
    stylesheet: "bootstrap.min.css"
    script: "bootstrap.min.js"
---

# Monthly Goals

## December Goals

*Knowing this is another short month due to the holidays, my monthly
goals are succinct and build upon existing progress.*

-   Get through eDNA bioinformatics pipeline from CALeDNA trip

   <div class="progress">
  <div class="progress-bar" role="progressbar" style="width: 20%;" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">20%</div>
</div>

-   Continue p450 manuscript draft

   <div class="progress">
  <div class="progress-bar" role="progressbar" style="width: 60%;" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100">60%</div>
</div>

-   Prepare SICB presentation for January

  <div class="progress">
  <div class="progress-bar" role="progressbar" style="width: 10%;" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100">10%</div>
</div>

-   Prepare Yellow Island website for January

  <div class="progress">
  <div class="progress-bar" role="progressbar" style="width: 15%;" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100">15%</div>
</div>

## November Goal Recap

-   Get through eDNA bioinformatics pipeline from CALeDNA trip

  <div class="progress">
  <div class="progress-bar" role="progressbar" style="width: 20%;" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">20%</div>
</div>

-   Outline & draft p450 manuscript

   <div class="progress">
  <div class="progress-bar" role="progressbar" style="width: 60%;" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100">60%</div>
</div>

-   Prepare poster for AGU in December

  <div class="progress">
  <div class="progress-bar" role="progressbar" style="width: 10%;" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100">10%</div>
</div>

## November Goal Reflection

*What worked, what didn't, where can I improve*

#### What Worked

-   Small amounts of daily progress over large chunks of work blocks
-   I was clear about my limitations and stuck to imminent projects.
    This resulted in going to AGU as a BIMS ambassador only instead of
    going as an ambassador and presenting.

#### What Didn't

-   I didn't make a comprehensive list of steps to accomplish each goal.
-   I didn't spend my time waiting for data to clarify the workflow for
    eDNA bioinformatics pipeline.

#### Improve

-   Prioritize workload and then create steps, it is clear that not all
    steps for all projects are a priority.
-   Work on switching tasks and making better documentation to support
    shifting between tasks to encourage overall progress, not just an
    'all or nothing' outcome.
-   Consistently schedule 'bench' time for coding and computer- based
    work at the beginning of the week when I do my weekly schedule
    review.
