---
title: "October 2023 Daily Notebook Post Log"
author: "Chris Mantegna"
date: "2023-10"
categories: ["monthly goals", "daily log"]
format:
  html:
    toc: true
---

# Daily Log

## 31 October 2023

## 30 October 2023
## 29 October 2023
## 28 October 2023
## 27 October 2023
## 26 October 2023
## 25 October 2023
## 24 October 2023
## 23 October 2023
## 22 October 2023
## 21 October 2023
## 20 October 2023
## 19 October 2023
## 18 October 2023
## 17 October 2023
## 16 October 2023
## 15 October 2023
## 14 October 2023
## 13 October 2023
## 12 October 2023
## 11 October 2023

- TA'd my last quiz section of the week, held office hours, finished grading discussion posts, and attended lecture for ENV 100
- Met with Matt re: Yellow Island project for summer 2024.
- Attended weekly FAB writing accountability meeting where I worked on updating my lab notebook.

## 10 October 2023

- TA'd for two of my quiz sections, worked on discussion post grading and quiz section grading.
- Attended SAFS Cafe.

## 09 October 2023

- Attended weekly teaching team meeting, reviewed course content, prepared for weekly TA sessions, and attended the lecture for ENV 100.
- Finalized calculations for BCA concentrations and reviewed SOD assay and sample preparation for next steps in the mussel work.
- I received the FINS Travel Award to cover the cost of my registration to SICB! It's not a huge amount, but it is pretty cool not to have it come out of pocket.

## 08 October 2023

- Sunday. Participated in the Dawg Dash 5k with friends and SAFS members to help raise scholarship fund money for UW.

## 07 October 2023

- Saturday. UWT lab time. I completed the test assay to determine sample dilution factor and then completed the BCA assays for all 127 samples in the first batch of the mussels. Went with a dilution factor of 5 so that all sample concentrations were within the range of the standards. All plates had both standards and samples in triplicate with a 'control' of sample #1 on each plate to help determine consistency in the plate reader. This will force sample #1 to only be run in duplicate vice triplicate when we begin the p450 assay on 10/12/23 due to reduced volume.

## 06 October 2023

- Attended my weekly FAB scheduling retrospective where we work together to trade tips and tools for maximizing productivity in our day while alotting time to relax and step away from tasks.
- Attended ENV 100 lecture and CENV Best Practices Teaching Course that helps me learn and use best practices in pedagogy as a TA.
- Prepped for lab work at UWT tomorrow.
## 05 October 2023

- UWT day. I finished the sample preparation for assays for the first 127 samples.
- Attended lab meeting where we discussed a paper I chose for our targeted content.
- Attended my weekly Black Grad Group Meeting. 
## 04 October 2023

- TA and lecture attendance of ENV 100. Held my first office hour which wasn't attended but afforded me the opportunity to get my first round of quiz section content graded.
- Attended the FAB Writing Accountability Group that we restarted from our summer break. It is really helpful to have a team of other SAFS grads that are further ahead than me to help me make progress.
- I applied for the SAFS FINS travel grant to pay for my SICB registration.
- 
## 03 October 2023

- Meeting with Steven to review GSAR/ annual progress report
- Innovation Grant Meeting, whole team, to finalize details on training, schedule, and logistics.
- Attended the SAFS Chat with Sam and Chelsea and heard a bit about their plan for the grad student experience
- TA'd my first two quiz sections

## 02 October 2023

- TA Meeting with ENVIRON 100 teaching team.
- Confirmed my committee meeting and sent invites, worked on my GSAR for Tuesday's meeting, prepared and confirmed tomorrows Innovation Grant meeting and agenda.
- Attended the E 100 lecture and prepared my slides for my quiz sections for tomorrow and Wednesday.

## 01 October 2023

- Sunday. Posted monthly goals and picked out a paper for this week's lab meeting.
