---
title: "May 2024 Daily Notebook Post Log"
author: "Chris Mantegna"
date: "2024-05-01"
categories: ["monthly goals", "daily log"]
format:
  html:
    toc: true
---

# Daily Log

# 31 May

# 30 May

# 29 May

# 28 May

# 27 May

# 26 May

# 25 May

# 24 May

# 23 May

# 22 May

# 21 May

# 20 May

# 19 May

# 18 May

# 17 May

# 16 May

# 15 May

# 14 May

# 13 May

# 12 May

# 11 May

# 10 May

# 09 May

- Attended Pubathon. Nop points for goals this week.
- Facilitated 401 today. Prof was out, so we continued working on our subsystem maps.
- Lab Meeting.

# 08 May

- 401 office hours and weekly assignment grading.
- Attended the BIMS Institute meeting where we discussed the use of Tidal Wave scholars for some of the needs of the program. We also went over the program budget and next steps.
- Met with Eily from the eDNA Collaborative to discuss possible collaborations.

# 07 May

- Reviewing 401 content for class today.
- Attended teaching team meeting and 401.
- Did some calendar/ meeting reconciliation for the REU and DDCSP students' deliverable before the program starts.
- Met with Steven to go over next steps for the mussel epigenetics work. We will split the 24 samples into the sites with the most contamination and the least contamination based on the analyte data from WDFW and the biomarker activity.
- Attended FAB writing accountability where I worked on getting my biomarker data organized to upload into my repo.

# 06 May

- Much needed organization and scheduling update day. I mapped out my current projects and steps to complete the associated tasks.

# 05 May

- Sunday
- Finished grading all assignments for 401.
- Put together a few visualizations and data tables for Ly with the associated markdown pdf.

# 04 May

- Saturday.

# 03 May

- Completed grading all papers for 401.
- Attended FAB accountability meeting.

# 02 May

- Met with Savannah at Sea Potential to discuss shift in workload due to personnel changes.
- Attended the last 30 minutes of Pubathon. No points for me this week as I didn't meet my goals of getting the raw data into the WDFW repo and completing 30% source annotation for the mussel biomarker paper.
- TA'd 401.
- Attended lab meeting where we discussed upcoming lab meeting content, bringing in undergrads for the summer, and plans for potential experiments.
- Attended the Husky 100 reception.

# 01 May

-   Started grading student essays and catching up on this week's
    content.
-   Monthly mentoring meeting with Julia.
-   Worked with Ly to pick out sites she'll evaluate for her capstone
    and talked through the visuals she'd like to use for her poster.
    We'll move forward with highly urbanized, less urbanized and
    reference for her project.
-   Set monthly goals for May.
