---
title: "January 2024 Goals"
author: "Chris Mantegna"
date: "2024-1"
categories: ["monthly goals", "daily entries"]
format:
  html:
    toc: true
html_dependencies:
  - name: "bootstrap"
    version: "4.3.1"
    src: "https://stackpath.bootstrapcdn.com"
    stylesheet: "bootstrap.min.css"
    script: "bootstrap.min.js"
---

# Monthly Goals

## January Goals

This is a month to reset, refocus, and be prepared to take on
opportunities as they come.

-   Clean up my GH repositories and lab website. <div class="progress">
  <div class="progress-bar" role="progressbar" style="width: 10%;" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100">10%</div>
</div>  


-   Clean up my calendars and set up a standing scheduler tool. <div class="progress">
  <div class="progress-bar" role="progressbar" style="width: 50%;" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">50%</div>
</div>


-   Clearly outline my writing time and writing objectives. <div class="progress">
  <div class="progress-bar" role="progressbar" style="width: 10%;" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100">10%</div>
</div>


## December Goal Recap

-   Get through eDNA bioinformatics pipeline from CALeDNA trip

::: progress
::: {.progress-bar role="progressbar" style="width: 20%;" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"}
20%
:::
:::

-   Continue p450 manuscript draft

::: progress
::: {.progress-bar role="progressbar" style="width: 20%;" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"}
20%
:::
:::

-   Prepare SICB presentation for January

::: progress
::: {.progress-bar role="progressbar" style="width: 50%;" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"}
50%
:::
:::

-   Prepare Yellow Island website for January

::: progress
::: {.progress-bar role="progressbar" style="width: 90%;" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"}
90%
:::
:::

## December Goal Reflection

*What worked, what didn't, where can I improve*

#### What Worked

-   Very little. It was difficult to stay on task, manage unexpected time- sucks and expected road blocks.  

#### What Didn't

-   It felt like everything went wrong at some point which is an
    indicator of overload. If things of varying magnitude feel
    overwhelming when they jump the track there isn't enough space to
    adjust. I was way too overloaded coming into the last month of the
    year and it showed.

#### Improve

-   Take whatever I believe I can accomplish and cut it in half.
-   Say 'No'.  
-   Move forward with attention and alignment. The days of saying yes to opportunities because they are presented are on their way out. 
