---
title: "March 2024 Daily Notebook Post Log"
author: "Chris Mantegna"
date: "2024-03-01"
categories: ["monthly goals", "daily log"]
format:
  html:
    toc: true
---

# Daily Log


# 31 March 

- Sunday.

# 30 March

- Saturday. 

# 29 March
# 28 March
# 27 March
# 26 March
# 25 March

- First day of Spring Quarter.
- **Courses/TA** I am TAing for ENVIR 401 - Analysis of Environmental Cases with Yen-Chu Weng. Classes are T/Th from 1030  - 1230, our teaching team meetings are from 1000 - 1030 on Tuesdays, and my office hours are on Wednesdays from 1000 - 1100 via Zoom.

# 24 March

- Sunday. Travelling. 

# 23 March

- Saturday. Travelling.

# 22 March
# 21 March
# 20 March
# 19 March
# 18 March
# 17 March

- Sunday.

# 16 March

- Saturday.

# 15 March
# 14 March
# 13 March
# 12 March

- **Research/ Bench Work** Cleaned up biomarker data and prepared my repo for access by others supporting the manuscript writing. I am creating a timetable/ timeline of what I need to accomplish daily to get this paper out. 
- **Administrative** I reached out to Molly and Mariko at WDFW for support with their whole tissue contamination data. We will meet on Tuesday 3.19 to go over details and how I can get that analysis completed.

# 11 March

- **Courses/TA** Finished grading my question in the short answer portion of the exam and completed my grading of the last discussion posts for the section.

# 10 March

- Sunday. Travelling.

# 09 March

- Saturday. Travelling.

# 08 March

- **Courses/TA** Administered the ENV 100 short answer final and took my turn in Zoom office hours to support the multiple choice portion.
- **Courses/TA** Started grading the short answer portion of the exam.
- Left campus and headed straight to the airport for Pakistan.

# 07 March

- **Meetings** Attended lab meeting where we went over projects in progress and attended Pubathon where we relayed current manuscript progress and goals for next week. I reached 2/3 goals for last week, netting me 7/10 points. This upcoming week I will focus on cleaning up my biomarker repo and setting up where I need help to meet the 3.31.24 deadline and to get the methods drafted.
- **Meetings** Met with Ly to go over her research questions, abstract, and SOP updates so that she can submit that for her capstone benchwork credit.
- **Meetings** **Administrative** I canceled the Innovation Grant Meeting. I dropped the ball on the follow through and reminders to the team requesting the completion of the actions items to keep us moving forward. I followed the cancellation with a task list and request for further clarification so that we could stay on track for the cohort arrival date of July 18th.

# 06 March

- **Courses/TA** Attended the last ENV 100 lecture of the quarter.
- **Writing** Finished the Nature draft and sent it to editor.
- **Writing** Started outlining/ adding bulleted points to the mussel biomarker draft.
- **Research/ Bench Work** I started gathering the sources into a Zotero library for the biomarker paper. I didn't annotate everything I added and that is a mistake to keep in mind for future me. I need to at least make a quick 2-3 sentences about what I am trying to understand with that paper. 

# 05 March

- **Writing** I worked on my Nature opinion draft. I reread the message from the editor and made it more specific to eDNA and field work instead of the general sequencing work I was discussing. I also tried to cement why space is important, but I am not sure I got there.
- **Coding** I worked on the quantitative addition to my goals page. I think I have to put a pin in this one and come back it at the end of the month when I have more time.

- **Research/ Bench Work** I started gathering the sources into a Zotero library for the biomarker paper. I didn't annotate everything I added and that is a mistake to keep in mind for future me. I need to at least make a quick 2-3 sentences about what I am trying to understand with that paper. 

# 04 March

- **Courses/TA** Attended ENV 100 lecture, teaching team meeting, and administered the final in two quiz sections.

- **Courses/TA** Completed grading for all assignments except the exam and final poster projects.

- **Administrative** I got my three papers on the Pubathon page and got my Nature draft to Steven for editing support. I also added my general project idea to an open GH issue for experiment ideas for a shellfish field project.
- **Coding** I worked on cleaning up the exploratory data visualizations. I was able to get the PCA loaded correctly but not the correlation plot with only the variables I want. 
- **Coding** I spent some time trying to add a quantitative portion to my monthly logs. I would like to count how many times one of ten tags was used throughout the month and create a pie chart or stacked bar by week to visualize how I'm spending my time. 

# 03 March

- Sunday. **Courses** Prepared for Monday quiz sections and wrapped up grading for the week.

# 02 March

- Saturday. **Writing** Worked on my Nature draft and got an early version to Julia for editing support.

# 01 March

- **Courses** Attended ENV 100 lecture and held my final quiz section for the week. 
- **Meetings** Met with Alison and Ly to discuss Ly's deliverables and the state of the data. We discussed the ranked plots, the kepler map, PCA plot, and correlation plot. Next steps are to clean up data as discussed with Steven earlier in the week.
