---
title: "January 2024 Daily Notebook Post Log"
author: "Chris Mantegna"
date: "2024-1"
categories: ["monthly goals", "daily log"]
format:
  html:
    toc: true
---

# Daily Log

## 31 January 2024

-   

## 30 January 2024

-   

## 29 January 2024

-   

## 28 January 2024

-   

## 27 January 2024

-   

## 26 January 2024

- Writing accountability session 1 of 2 with Taylor this morning. I used this early time to catch up on emails and prep for my quiz section weekly round-up emails to set students up for the following week.
- Attended ENV lecture, led my final quiz section for the week and sent out the weekly ENV round-up to all three of my quiz sections in preparation with action items to prepare for the upcoming midterm.
- Met with ENV students for Office Hour.
- Attended weekly FAB Retros meeting where we setup schedules and research goals for next week.
- Attended Gardell Lab meeting where we shared our progress YTD and Winter Quarter goals. My goals center around data analysis and manuscript writing for the Biomarkers paper, Homo-aquaticus manuscript summary and eDNA presentation.
- Held writing accountability 2 of 2 with Taylor. I worked on streamlining the SOD protocol after performing the assay on Thursday. I also completed the calculations on the assay ran yesterday. There are some plating errors and most of the final values are out of range. I will go into the lab tomorrow to run my BCAs to check protein concentration and then rerun the SOD to ensure there was no operator error to account for the extreme variability of the current result.

## 25 January 2024

-   UWT lab day. We completed all homogenizations for the SOD assay. We made the stock buffers and ran our first plate. Quick plotting looks like there are a few values that fall outside of the standard curve set by the assay standards. I will verify my calculations to determine if we need to dilute the samples, but for now it looks like we can run as outlined in the assay protocol from the manufacturer.
- I received my abstract confirmation for presentation from UN Ocean Decades. I will be presenting in Session 4, Community engaged science and mentorship, where I will present about my Yellow Island work. I'm definitely excited.

## 24 January 2024

- Attended ENV lecture, made quiz section assignments for next week's role play, and started grading the outside seminar papers.
- Completed the Yellow Island Site application for the 2024 DDCSP cohort.
- Attended Black Grad Group
- Attended the Michael Twitty Townhall Lecture. It was engaging to hear him speak of his journey, the focus of his book The Cooking Gene, and his exploration of his lineage and identities through following the food and culture of Southern Black descendents of the enslaved.
- Evening Working Session with Taylor. I worked on incorporating the scholar's feedback on the Yellow Island website, got the summer tide schedule predictions over to Melissa at DDCSP so we could work on housing, finished cleaning up the p450 data and began a bit of analysis.
- Read Chapter 5 in Race After Technology.

## 23 January 2024

-  UWT lab day. Ly and I finished all tissues dissections for the SOD assay and began the homogenizations to prepare for assaying. We were also able to start consolidating samples and putting a few things away that we won't need to access regualarly.

## 22 January 2024

- Attended ENV 100 lecture and teaching team meeting.
- Led two quiz sections through the Indigenous walking tour and content review guide in preparation for the midterm.
- Attended the FAB writing accountabilty session where I worked on cleaning up the full p450 dataset. I started putting all of the samples together by site and verfiying all BCA and p450 values were calculated correctly, sought out outliers to double check, and started grouping by site for analysis later this week.
- Reviewed the SOD protocol from the manufacturer as well as the modified protocol we already had. 

## 21 January 2024

- Sunday. Completed some grading and prepared for quiz section.
- Worked on the manuscript summary for the Homo-aquaticus special issue due to Frontiers at the end of the week. I created an annotated bibliography to keep track of resources and writing direction. Once this is complete I want to run it past Jose and then invite Corey to write with us.

## 20 January 2024

- Saturday. Watched my Ravens take out the Texans!

## 19 January 2024

- Accountability writing hour with Taylor and FAB weekly retros.
- Attended ENV 100 lecture and held office hour.
- Opened an issue for my inability to load packages on Raven despite always having access. Sam responded with some options to get the packages to load.

## 18 January 2024

- Attended lab meeting and met with Steven later in the day to discuss the progess on a few projects I am working on.
- Spent time working on the literature review for a manuscript summary due next week.

## 17 January 2024

- Attended ENV lecture and held office hours.
- Had my monthly mentorship meeting with Julia and met with Jose to discuss authoring an article together.
- Started working on the p450 data. I completed the BCA protein calculations and the subsequent p450 values normalized by the protein concentrations. These values are aligned with the rest of the redo so I can move forward with analysis.

## 16 January 2024

- UWT lab day. I finished the qc run for the BCA assay and the last samples for the p450 assay. All data is in hand for this assay, finally. Ly and I talked through next steps with the SOD assays. The tissue homogenization process is two steps and straight to assay, so the feasibility of completing SOD assays by the end of the month is highly likely.

## 15 January 2024

- Monday. I spent today working on my Hall application. I am not going to move forward with the application. I want something a bit more aligned with my end goal. I have to tie my larger scale ecosystem work to my mechanistic interrogation and I believe a combination of metabolomics and microbiome work on mytilus can be that bridge. 
- FAB writing accountability meeting.

## 14 January 2024

- Sunday. Worked on my bypass package, mainly my MS thesis.
- Finished grading for the week and sent the weekly round-up email to the quiz sections.

## 13 January 2024

- Saturday. Off.

## 12 January 2024

- Attended ENV lecture and led quiz section.
- Held writing accountability with Taylor. I worked on p450 methods and some ideas for my Hall Conservation Proposal.
 - FAB schedule retro and teaching evaluation review.

## 11 January 2024

- UWT lab day. Ly finished pulling out tissue for the p450 redo and made it to the halfway mark on tissue dissection for SOD assay prep. I finished homogenate processing for the last 75 samples for the p450 QC run. Next step is to plate and run BCA and p450 to compare to the tests for BFC test and initial p450 results.
- Attended lab meeting but left after 30 minutes to attend to a tank failure in the Gardell lab that was leaking water across the floor.
- Met with WDFW folks to discuss authorship and results on the p450 paper. In addition to myself, Steven and Alison we will be adding Mariko, Danielle and Molly from WDFW.
- Attended the Salish Sea Institute webinar "Sharing Knowledge Across Disciplines & Borders" where I learned about the initiatives of the WWU- housed organization and some opportunities to work with them when doing Salish Sea work.

## 10 January 2024

- Attended ENV 100 lecture and started grading.
- Met with Jose to discuss an upcoming mentor call and potential co-authorship on a paper about ocean science pedagogy.
- Met with Matt to work out basic logistics for the 2024 Yellow Island season.
- Reviewed p450 work from the day prior. The plate shows the appropriate gradation in BFC across all three mediums (microsomal buffer, DI water, and sample). The blanks were a bit inconsistent, but the rest of the result lends itself as confirmation that the preliminary results we got in December were accurate. Ly and I will rerun the last batch of 75 samples with odd BCA values in the next few days.

## 09 January 2024

- UWT lab day. I updated the tissue prep protocol for the p450 assays to mitigate some of the interference we saw in the first round of data acquisition. After that I ran a test assay to assess fluorescence levels with the BFC across a gradient, with and without sample, and with and without buffer and DI water. 

## 08 January 2024

- Attended ENV lecture, teaching team meeting, and led two of my three quiz sections.
- Watched my Huskies lose the CFP to Michigan.

## 07 January 2024

- Sunday. Prepared for upcoming week and quiz sections.

## 06 January 2024

- Saturday. Attended SICB.

## 05 January 2024

-  Writing accountability with Taylor where I worked on Yellow Island program review.
- Attended ENV lecture.
- Attended SICB and made my first conference presentation. I presented on using eDNA for biodiversity assessment in complement with physical methods.

## 04 January 2024

- Attended SICB in the morning.
- Worked on my SICB presentation in the afternoon and  evening.

## 03 January 2024

-   Worked on my presentation storyline.
-   Attended ENV 100 lecture.
-   Attended SICB. Watched Zach's talk, setup posters with Logan and the
    REU students from the summer and then attended the poster session.

## 02 January 2024

-   Attended MISS special mentorship symposium and checked into SICB.
-   Completed the preliminary Yellow Island Program website and prepared
    for lecture and TA meeting this week.

## 01 January 2024

-   New Years Day. Seattle Sports Day! Go Kraken! Go Huskies!
